import type { TaskCategory } from './task';
import type { BodyTransformationMode } from './mode';

export interface WeeklyTask {
  id: string;
  text: string;
  category: TaskCategory;
  daysOfWeek: number[]; // 0-6, where 0 = Sunday
  active: boolean;
  createdAt: number; // timestamp
  isSuggested?: boolean; // Marks if this was AI-suggested
}

export interface WeeklyTasksState {
  [id: string]: WeeklyTask;
}

/**
 * Suggested workout with intensity and focus
 */
export interface SuggestedWorkout {
  id: string;
  title: string;
  category: TaskCategory;
  intensity: 'low' | 'moderate' | 'high';
  primaryFocus: 'fatLoss' | 'muscle' | 'balanced';
  dayOfWeek: number; // 0-6, where 0 = Sunday
  description?: string; // Optional details about the workout
  isSuggested: true;
  weekStartDate: string; // YYYY-MM-DD
}

/**
 * Weekly workout plan generated by AI
 */
export interface WeeklyWorkoutPlan {
  id: string;
  weekStartDate: string; // YYYY-MM-DD (Monday of the week)
  mode: BodyTransformationMode;
  workouts: SuggestedWorkout[];
  recoveryScore: number; // 0-100 (from analytics)
  completionConsistency: number; // 0-100 (from analytics)
  createdAt: number; // timestamp
}
